/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 6eda92134c3bf54209c31118d5564693)
interface __BaseEnv_Env {
	DB: D1Database;
	PHASE: "1-workers-d1";
	ARENA_INVITE_TOKEN: string;
	CURATOR_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PHASE" | "ARENA_INVITE_TOKEN" | "CURATOR_API_KEY">> {}
}
declare module "*.md" {
	const value: string;
	export default value;
}
declare module "*.txt" {
	const value: string;
	export default value;
}